project:
  type: website
  output-dir: docs

website:
  title: "exploring the digital market"
  page-navigation: true
  reader-mode: true
  favicon: "images/icon.png"
  navbar:
    tools:
      - icon: github
        href: https://github.com/BrookemWalters/digitaleccon
        text: "gitHub organization"
      - icon: linkedin
        href: https://www.linkedin.com/in/bmwlters
        text: "LinkedIn"
    search: true
    collapse-below: lg
    type: dark
    logo: "images/icon.png"
    left: 
    - text: home
      href: dm.qmd
    - text: citations
      href: citations.qmd 
  page-footer:
    background: "#DBE55F"    
    right: "Brooke Walters 2024" 
    left: "This page is built with ☕ and [Quarto](https://quarto.org/)."

format:
  html:
    code-fold: true
    code-summary: "Show the code"
    theme: minty
    css: styles.css
    toc: true

editor: visual

