# de_employment$SubAttribute <- factor(
#   de_employment$SubAttribute,
#   levels = c( # doing this manually because the grouping didnt work
# "Computer systems design and related services",
# "Wholesale trade",
# "Broadcasting and telecommunications",
# "Computer and electronic products",
# "Publishing industries, except internet (includes software)",
# "Data processing, internet publishing, and other information services",
# "Other retail",
# "Miscellaneous professional, scientific, and technical services",
# "Motion picture and sound recording industries",
# "Educational services",
# "Food and beverage stores",
# "Motor vehicle and parts dealers",
# "Management of companies and enterprises",
# "Truck transportation",
# "Machinery",
# "General government",
# "Electrical equipment, appliances, and components",
# "Educational services, health care, and social assistance",
# "Nondurable goods",
# "General merchandise stores",
# "Nondefense",
# "Miscellaneous manufacturing",
# "Insurance carriers and related activities",
# "Federal Reserve banks, credit intermediation, and related activities",
# "National defense",
# "Accommodation and food services",
# "Fabricated metal products",
# "Motor vehicles, bodies and trailers, and parts",
# "Air transportation",
# "Arts, entertainment, and recreation",
# "Warehousing and storage",
# "Other transportation and support activities",
# "Other transportation equipment",
# "Securities, commodity contracts, and investments",
# "Construction",
# "Furniture and related products",
# "Government enterprises",
# "Legal services",
# "Nonmetallic mineral products",
# "Primary metals",
# "Real estate",
# "Rental and leasing services and lessors of intangible assets",
# "Utilities",
# "Wood products" ))
